server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8432/db_ecommerce
    username: postgres
    password: Piseth1711*#
  application:
    name: ecommerce
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
file-upload:
  client-path: /file
  server-path: D:/ISTAD/Year 2/Semester 2/Back-end Dev II/Code/fileupload/
  base-uri: http://localhost:${server.port}${file-upload.client-path}
keycloak:
  server-url: http://localhost:9091
  client-id: client-test
  client-secret: 5VSuYuq0pUBrMfOyiaEwmQq290Bbxrfx5Yygz0j50RASkHRZ5azfZ2duGKJTAOCkFpOc7J6oqqzkDU1FveAMEf
  realm: ecommerce
springdoc:
  swagger-ui:
    oauth:
      client-id: next-js
      client-secret: U9sIYC0kHpaCNDs0DHen19YsW9enBlwD8H2tVYkLEgxiUThcOhlKMl55TWvZ2GCtVecROsP4VuNzTivwIbt6pQ
      use-pkce-with-authorization-code-grant: true
